/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const dev = false;

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(dev?'http://localhost:3000/monsite/iconeaide.glb':'/monsite/iconeaide.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(()=>{
	  actions.Wait_Action.play();
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.spine} />
      <skinnedMesh geometry={nodes.Cube_1.geometry} material={materials.Material} skeleton={nodes.Cube_1.skeleton} />
      <skinnedMesh
        geometry={nodes.Cube_2.geometry}
        material={materials.Mouth_Material}
        skeleton={nodes.Cube_2.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube_3.geometry}
        material={materials.Hairf_Material}
        skeleton={nodes.Cube_3.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube_4.geometry}
        material={materials.Shire_Material}
        skeleton={nodes.Cube_4.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube_5.geometry}
        material={materials.Pants_Material}
        skeleton={nodes.Cube_5.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube_6.geometry}
        material={materials.Shoe_Material}
        skeleton={nodes.Cube_6.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube_7.geometry}
        material={materials.Default_Eye_Material}
        skeleton={nodes.Cube_7.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube_8.geometry}
        material={materials.Eye_Black_Mateiral}
        skeleton={nodes.Cube_8.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Cube_9.geometry}
        material={materials.Eye_Black_2_material}
        skeleton={nodes.Cube_9.skeleton}
      />
    </group>
  )
}

useGLTF.preload(dev?'http://localhost:3000/monsite/iconeaide.glb':'/monsite/iconeaide.glb')

//remove home page from package.json to debugger
// "homepage": "https://technoetienne.github.io/monsite",
